defaults:
  force: false
  dry_run: false
  max_retries: 3
  timeout_seconds: 30

waves:
  MVP-1:
    - ibge_admin_fetch
    - ibge_geometries_fetch
    - ibge_indicators_fetch
    - dbt_build
    - quality_suite
  MVP-2:
    - tse_catalog_discovery
    - tse_electorate_fetch
    - tse_results_fetch
    - quality_suite
  MVP-3:
    - education_inep_fetch
    - health_datasus_fetch
    - finance_siconfi_fetch
    - labor_mte_fetch
    - quality_suite
  MVP-4:
    - sidra_indicators_fetch
    - senatran_fleet_fetch
    - sejusp_public_safety_fetch
    - siops_health_finance_fetch
    - snis_sanitation_fetch
    - quality_suite
  MVP-5:
    - inmet_climate_fetch
    - inpe_queimadas_fetch
    - ana_hydrology_fetch
    - anatel_connectivity_fetch
    - aneel_energy_fetch
    - quality_suite
  MVP-6:
    - suasweb_social_assistance_fetch
    - cneas_social_assistance_fetch
    - portal_transparencia_fetch
    - cecad_social_protection_fetch
    - censo_suas_fetch
    - quality_suite
  MVP-7:
    - urban_roads_fetch
    - urban_pois_fetch
    - quality_suite

jobs:
  ibge_admin_fetch:
    reference_period: "2026"
  ibge_geometries_fetch:
    reference_period: "2026"
  ibge_indicators_fetch:
    reference_period: "2026"
  tse_catalog_discovery:
    reference_period: "2024"
  tse_electorate_fetch:
    reference_period: "2024"
  tse_results_fetch:
    reference_period: "2024"
  education_inep_fetch:
    reference_period: "2025"
  health_datasus_fetch:
    reference_period: "2025"
  finance_siconfi_fetch:
    reference_period: "2025"
  labor_mte_fetch:
    reference_period: "2025"
  sidra_indicators_fetch:
    reference_period: "2025"
  senatran_fleet_fetch:
    reference_period: "2025"
  sejusp_public_safety_fetch:
    reference_period: "2025"
  siops_health_finance_fetch:
    reference_period: "2025"
  snis_sanitation_fetch:
    reference_period: "2025"
  inmet_climate_fetch:
    reference_period: "2025"
  inpe_queimadas_fetch:
    reference_period: "2025"
  ana_hydrology_fetch:
    reference_period: "2025"
  anatel_connectivity_fetch:
    reference_period: "2025"
  aneel_energy_fetch:
    reference_period: "2025"
  suasweb_social_assistance_fetch:
    reference_period: "2025"
  cneas_social_assistance_fetch:
    reference_period: "2025"
  portal_transparencia_fetch:
    reference_period: "2025"
  cecad_social_protection_fetch:
    reference_period: "2025"
  censo_suas_fetch:
    reference_period: "2025"
  urban_roads_fetch:
    reference_period: "2026"
  urban_pois_fetch:
    reference_period: "2026"
  dbt_build:
    reference_period: "2026"
  quality_suite:
    reference_period: "2026"
