defaults:
  min_rows_after_filter: 1
  max_missing_ratio: 0.00
  max_negative_rows: 0

dim_territory:
  min_district_count: 1
  max_geometry_missing_ratio: 0.00
  max_empty_geometry_rows: 0
  max_invalid_geometry_rows: 0

fact_electorate:
  min_rows_after_filter: 1
  max_negative_rows: 0
  max_missing_ratio: 0.00

fact_election_result:
  max_negative_rows: 0
  max_missing_ratio: 0.00

fact_indicator:
  max_missing_ratio: 0.00
  max_source_probe_rows: 0
  min_rows_sidra: 1
  min_rows_senatran: 1
  min_rows_sejusp_mg: 1
  min_rows_siops: 1
  min_rows_snis: 1

ops_pipeline_runs:
  min_successful_runs_per_job: 1
