defaults:
  min_rows_after_filter: 1
  max_missing_ratio: 0.00
  max_negative_rows: 0

dim_territory:
  min_district_count: 1
  min_electoral_zone_count: 1
  max_geometry_missing_ratio: 0.00
  max_empty_geometry_rows: 0
  max_invalid_geometry_rows: 0
  max_electoral_zone_orphans: 0
  max_electoral_zone_missing_canonical_key: 0

fact_electorate:
  min_rows_after_filter: 1
  max_negative_rows: 0
  max_missing_ratio: 0.00
  min_distinct_years: 2
  min_electoral_zone_rows: 1
  max_year_gap: 2

fact_election_result:
  max_negative_rows: 0
  max_missing_ratio: 0.00
  min_distinct_years: 2
  min_electoral_zone_rows: 1
  max_year_gap: 2

fact_indicator:
  max_missing_ratio: 0.00
  max_source_probe_rows: 0
  min_distinct_periods: 3
  min_source_distinct_periods_default: 2
  min_periods_cecad: 0
  min_periods_censo_suas: 0
  min_rows_level_municipality: 1
  min_rows_level_district: 1
  min_rows_level_census_sector: 1
  min_rows_sidra: 1
  min_rows_senatran: 1
  min_rows_sejusp_mg: 1
  min_rows_siops: 1
  min_rows_snis: 1
  min_rows_inmet: 1
  min_rows_inpe_queimadas: 1
  min_rows_ana: 1
  min_rows_anatel: 1
  min_rows_aneel: 1
  min_rows_cecad: 0
  min_rows_censo_suas: 0

fact_social_protection:
  min_rows_after_filter: 0
  max_negative_rows: 0
  max_empty_metric_rows: 0

fact_social_assistance_network:
  min_rows_after_filter: 0
  max_negative_rows: 0
  max_empty_metric_rows: 0

urban_domain:
  min_road_rows: 1
  min_poi_rows: 1
  max_invalid_geometry_rows: 0

ops_pipeline_runs:
  min_successful_runs_per_job: 1
