defaults:
  min_rows_after_filter: 1
  max_missing_ratio: 0.00
  max_negative_rows: 0

dim_territory:
  min_district_count: 1
  min_electoral_zone_count: 1
  max_geometry_missing_ratio: 0.00
  max_empty_geometry_rows: 0
  max_invalid_geometry_rows: 0
  max_electoral_zone_orphans: 0
  max_electoral_zone_missing_canonical_key: 0

map_layers:
  min_rows_municipality: 1
  min_geometry_ratio_municipality: 1.00
  min_rows_district: 1
  min_geometry_ratio_district: 1.00
  min_rows_census_sector: 1
  min_geometry_ratio_census_sector: 0.00
  min_rows_electoral_zone: 1
  min_geometry_ratio_electoral_zone: 0.00
  min_rows_electoral_section: 1
  min_geometry_ratio_electoral_section: 0.00

fact_electorate:
  min_rows_after_filter: 1
  max_negative_rows: 0
  max_missing_ratio: 0.00
  min_distinct_years: 2
  min_electoral_zone_rows: 1
  max_year_gap: 2

fact_election_result:
  max_negative_rows: 0
  max_missing_ratio: 0.00
  min_distinct_years: 2
  min_electoral_zone_rows: 1
  max_year_gap: 2

fact_indicator:
  max_missing_ratio: 0.00
  max_source_probe_rows: 0
  min_distinct_periods: 3
  min_source_distinct_periods_default: 2
  min_periods_inmet: 5
  min_periods_inpe_queimadas: 5
  min_periods_ana: 5
  min_periods_cecad: 0
  min_periods_censo_suas: 0
  min_rows_level_municipality: 1
  min_rows_level_district: 1
  min_rows_level_census_sector: 1
  min_rows_datasus: 1
  min_rows_inep: 1
  min_rows_siconfi: 1
  min_rows_mte: 1
  min_rows_tse: 1
  min_rows_sidra: 1
  min_rows_senatran: 1
  min_rows_sejusp_mg: 1
  min_rows_siops: 1
  min_rows_snis: 1
  min_rows_inmet: 1
  min_rows_inpe_queimadas: 1
  min_rows_ana: 1
  min_rows_anatel: 1
  min_rows_aneel: 1
  min_rows_cecad: 0
  min_rows_censo_suas: 0

fact_social_protection:
  min_rows_after_filter: 0
  max_negative_rows: 0
  max_empty_metric_rows: 0

fact_social_assistance_network:
  min_rows_after_filter: 0
  max_negative_rows: 0
  max_empty_metric_rows: 0

urban_domain:
  min_road_rows: 1
  min_poi_rows: 1
  min_transport_rows: 0
  max_invalid_geometry_rows: 0

environment_risk:
  min_rows_district: 1
  min_rows_census_sector: 1
  min_distinct_periods: 1
  max_null_risk_score_rows: 0
  max_null_hazard_score_rows: 0
  max_null_exposure_score_rows: 0
  min_mart_rows_municipality: 1
  min_mart_rows_district: 1
  min_mart_rows_census_sector: 1
  min_mart_distinct_periods: 1
  max_mart_null_score_rows: 0

schema_contracts:
  min_active_coverage_pct: 100.0
  max_missing_connectors: 0

schema_drift:
  max_missing_required_columns: 0
  max_type_mismatch_columns: 0
  max_connectors_with_drift: 0

ops_pipeline_runs:
  min_successful_runs_per_job: 1
